### ISSUE TITLE
Don't open bookmarks in sidebar

### ISSUE THREAD

**Issue by bbrnobby** [piroor/openbookmarkintab#4]
ブックマークのプロパティから "このブックマークはサイドバーに読み込む" の設定をオンにしている状態でも、サイドバーからではなく新しいタブで開いてしまいます。

**Comment by piroor** [comment]
ありがとうございます、見落としていました。 8f3a86634fce24cb857d909014478b28d252a409 で直りました。

**Comment by bbrnobby** [comment]
対応有難うございます。いつも便利に使わせていただいてます。
